name: "ci-linting"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dev dependencies
        run: |
          pip install poetry
          poetry install --only=dev

      - name: Linting
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files
